### ISSUE TITLE
SSL错误,请问如何处理

### ISSUE THREAD

**Issue by wxchil** [hotinewang/4KSJ_AutoSignin#2]
报错如下,请帮助看看如何解决?非常感谢~!
ssl.c:990: The handshake operation timed out

![image](https://github.com/hotinewang/4KSJ_AutoSignin/assets/44988562/ffdf6d59-c797-4231-8ccb-91e7a8e5353d)

**Comment by hotinewang** [comment]
你修改除了用户名密码之外的代码了吗？如果没改，是不是开代理了?用你的服务器ping一下4ksj服务器看看是否能通。我这边目前使用正常。

**Comment by wxchil** [comment]
好，那应该是我这边网络的问题，谢谢
