### ISSUE TITLE
脚本请求登录总是提示密码错误，但是我实际登录就可以

### ISSUE THREAD

**Issue by shixiangkuangmo** [hotinewang/4KSJ_AutoSignin#5]
脚本请求登录总是提示密码错误，但是我实际登录就可以，中文用户名是不是没有把中文转义正确呢？？

**Comment by hotinewang** [comment]
有可能吧，我没测试过中文用户名。你可以试一下把第10行：
`uname = '*******'            # username，需要修改成自己的登录用户名！！！！！！！！！！！！！！！！！！！！`
改成下边的样子。（可以试一下能不能成功）：
```
uname = '*******'            # username，需要修改成自己的登录用户名！！！！！！！！！！！！！！！！！！！！
uname = quote(uname)
````

**Comment by shixiangkuangmo** [comment]
> maybe, I haven't tested Chinese username. You can try to change line 10: 'uname = '********' # username, you need to change it to your own login username!!!!!!!!!!!!!!!!!!! ' Change it to the following. (You can try to see if it succeeds):
> 
> ```
> uname = '*******' # username, you need to change it to your own login username!!!!!!!!!!!!!!!!!!!
> uname = quote(uname)
> ```

Nor does it work

**Comment by shixiangkuangmo** [comment]
> 有可能吧，我没测试过中文用户名。你可以试一下把第10行： `uname = '*******' # username，需要修改成自己的登录用户名！！！！！！！！！！！！！！！！！！！！` 改成下边的样子。（可以试一下能不能成功）：
> 
> ```
> uname = '*******'            # username，需要修改成自己的登录用户名！！！！！！！！！！！！！！！！！！！！
> uname = quote(uname)
> ```

好像也不行 你试试呢  uname:”食翔狂魔“    password:“a82664730”

**Comment by hotinewang** [comment]
我发现代码不用动，你把用户名那里，改成你的id编号就可以了。亲测已签到成功：）
`uname = '1379065'`

**Comment by shixiangkuangmo** [comment]
> 我发现代码不用动，你把用户名那里，改成你的id编号就可以了。亲测已签到成功：） `uname = '1379065'`

好的，感谢
