### ISSUE TITLE
12-15日报错

### ISSUE THREAD

**Issue by CelestialRipple** [hotinewang/4KSJ_AutoSignin#6]
日志如下
登录成功
获取到个人空间入口:https://www.4ksj.com/space-uid-1062716.html
line: 159 ValueError("unknown url type: '/%E8%BF%99%E6%AE%B5%E6%90%9E%E4%B8%8D%E5%AE%9A%E7%9A%84%E8%AF%9D%E8%AF%B7%E7%A7%81%E4%BF%A1...'")
尝试第1次
准备登录，获取到登录页formhash: d89626c8
line: 149 IndexError('list index out of range')
尝试第2次
准备登录，获取到登录页formhash: d89626c8
line: 149 IndexError('list index out of range')

**Comment by xuexijiaoben** [comment]
兄弟，你解决了么？我也是这个问题

**Comment by hotinewang** [comment]
代码113行的链接需要替换下
